bongodev/appointment-booking

- server/src/middlewares/authenticate.js
> Fix bug in authenticate middleware in server

- client/src/pages/HomePage.tsx
https://github.com/bongodev/appointment-booking/issues/44
Removed the user fetching and logout button functionalities from the Homepage
> Remove user fetching and logout button from HomePage

- server/package.json
- server/src/app.js
- server/src/config/index.js
- server/src/config/logger.js
- server/src/db.js
- server/src/middlewares/errorHandler.js
- server/yarn.lock
Added logger for backend and implemented them in the server code
> [Sumiya] Added logger for backend 

- server/src/controllers/index.js
- server/src/controllers/slot.js
- server/src/middlewares/index.js
- server/src/middlewares/validationMiddleware.js
- server/src/models/index.js
- server/src/models/slot.js
- server/src/routers/index.js
- server/src/routers/slot.js
- server/src/schemas/index.js
- server/src/schemas/mixin.js
- server/src/schemas/slot.js
- server/src/services/index.js
- server/src/services/slot.js
> [Nazma] Add CRUD API's for slots

- client/package.json
- client/src/components/AdminSidebar.tsx
- client/yarn.lock
> Add admin penel sidebar

- server/src/services/signup.js
> Hide password field in singup api response

- client/src/pages/SignupPage.tsx
> [Nazma] Add log in url at sign up page

- server/eslint.config.js
- server/package.json
- server/src/app.js
- server/src/config/index.js
- server/yarn.lock
Eslint has been added to the backend for better code quality and to avoid unexpected bugs like missing semicolon, using console log, unused variables etc.
> [Nazma] Add lint for backend

- server/package.json
> Move pino-pretty from dependencies to dev-dependencies

- server/.prettierignore
- server/.prettierrc.js
- server/package.json
- server/yarn.lock
> [Promi] Add prettier-issue-39

- server/src/controllers/slot.js
- server/src/services/slot.js
Click here to see the documentation [here](https://documenter.getpostman.com/view/20010455/2sAYkGKKHh#17f4c68e-5b1b-4dbc-8fb0-5c800bc18f92)
> Add Pagination Support to Get Slots API

- server/src/controllers/index.js
- server/src/controllers/roleController.js
- server/src/models/index.js
- server/src/models/role.js
- server/src/routers/index.js
- server/src/routers/roleRouter.js
- server/src/schemas/index.js
- server/src/schemas/role.js
- server/src/services/index.js
- server/src/services/userRole.js
> Add user role

- server/src/controllers/index.js
- server/src/controllers/userProfile.js
- server/src/models/index.js
- server/src/models/user.js
- server/src/models/userProfile.js
- server/src/routers/index.js
- server/src/routers/userProfile.js
- server/src/schemas/index.js
- server/src/schemas/user.js
- server/src/schemas/userProfile.js
- server/src/services/index.js
- server/src/services/signup.js
- server/src/services/userProfile.js
Adds complete CRUD functionality for user profiles, where signing up automatically creates a profile. Soft deletion is implemented for both profiles and linked users
> [Sumiya] Add crud for user profile -Issue 47

- client/package.json
- client/src/hooks/index.ts
- client/src/hooks/useCurrentUser.tsx
- client/yarn.lock
> [Sumiya] Add useCurrentUser hook

- server/src/app.js
- server/src/schemas/pagination.js
> Add pagination schema

- client/.dockerignore
- client/Dockerfile
- compose.yml
- server/.dockerignore
- server/Dockerfile
https://github.com/bongodev/appointment-booking/issues/84
Dockerized the whole app
> Dockerize the appointment booking app

- client/src/components/MenuItemList.tsx
- client/src/components/TopNavBar.tsx
- client/src/hooks/index.ts
- client/src/hooks/useLogout.tsx
1. Extracted the menu item rendering logic into a dedicated MenuItemList component for better reusability and cleaner structure
2.  Integrated react-router's NavLink to handle internal navigation for menu items like Profile, Account, and Dashboard.
3. Handled the Logout functionality using a custom useLogout hook.
> Show user information in top navbar

- client/src/hooks/useCurrentUser.tsx
- client/src/providers/AppProvider.tsx
> [Sumiya] Create App provider and wrap the application with app provider [Updated]

- .gitignore
- server/src/utils/customErrors.js
Added NotFoundError class, BadRequestError class and UnauthorizedError class
> Add Custom error class

- server/src/controllers/auth.js
- server/src/controllers/index.js
- server/src/controllers/user.js
- server/src/middlewares/index.js
- server/src/routers/userRoute.js
- server/src/schemas/user.js
- server/src/services/index.js
- server/src/services/user.js
Here is the documentation of this Api [Click here](https://documenter.getpostman.com/view/20010455/2sAYkGKKHh#fd90cf7d-bcb3-4b95-a721-8013c672b076)
> Update user API

- client/src/hooks/index.ts
- client/src/hooks/useProfileUpdate.ts
- client/src/hooks/useUserUpdate.ts
- client/src/main.tsx
- client/src/pages/Profile.tsx
- client/src/schema/index.ts
- client/src/schema/profile.ts
- client/src/services/index.ts
- client/src/services/profile.ts
- client/src/services/user.ts
User can view profile page and update profile information.
> Add profile page and profile update functionality

- client/src/pages/index.ts
> Remove admin route from index.ts

- client/src/config/http.ts
- server/src/controllers/auth.js
1. Increased refreshed token expiry time
2. Store dnew access token after refreshing
> Fix refresh token functionality

- client/src/components/AppLogo.tsx
- client/src/components/index.ts
- client/src/components/navigation/Sidebar.tsx
- client/src/components/navigation/TopNavBar.tsx
- client/src/pages/HomePage.tsx
- client/src/pages/RootLayout.tsx
This pr solved the following issue
Clicking on the logo does not route to the homepage
Remove the left and right spaces for navbar content
> Update homepage UI
